language: node_js
node_js:
  - '6'

cache:
  directories:
    - $HOME/.npm
    - node_modules

services:
  - postgresql

before_script:
  - psql -c 'create database calbhangra;' -U postgres

script:
  - npm run cover
  - bash <(curl -s https://codecov.io/bash)

env: >
  - CXX=g++-4.8
  - NODE_CONFIG='{"postgres": {"password": ""}}'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
