language: node_js
node_js:
  - '6'

services:
  - postgresql

before_script:
  - psql -c 'create database calbhangra;' -U postgres
  - npm i codecov

script:
  - npm run ci

env: >
  - CXX=g++-4.8
  - NODE_CONFIG='{"postgres": {"password": ""}}'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
